confirm-before-quit = true
adaptive-theme = { dark = "yazelix-dark", light = "yazelix-light" }

[renderer]
backend = "Webgpu"
custom-shader = [
  "@mars_shader_dir@/cursor_trail_dusk.glsl",
  "@mars_shader_dir@/generated_effects/sweep.glsl",
  "@mars_shader_dir@/generated_effects/rectangle_boom.glsl",
]

[window]
decorations = "Disabled"

[cursor]
blinking = true
blinking-interval = 650

[effects]
trail-cursor = true

@mars_fonts@
