confirm-before-quit = true
adaptive-theme = { dark = "yazelix-dark", light = "yazelix-light" }

[renderer]
backend = "Webgpu"

[window]
decorations = "Disabled"

[cursor]
blinking = true
blinking-interval = 650

[effects]
trail-cursor = true

@yazelix_terminal_fonts@
