[colors]
background = "#0F0D0E"
foreground = "#FFFFFF"
cursor = "#F712FF"
vi-cursor = "#12D0FF"

black = "#393A3D"
red = "#FF1261"
green = "#2AD947"
yellow = "#FCBA28"
blue = "#2D9AFF"
magenta = "#DD30FF"
cyan = "#17D5DF"
white = "#E7E7E7"

light-black = "#6B6B6B"
light-red = "#C55555"
light-green = "#AAC474"
light-yellow = "#FECA88"
light-blue = "#82B8C8"
light-magenta = "#C28CB8"
light-cyan = "#93D3C3"
light-white = "#F8F8F8"

tabs = "#424040"
tab-border = "#696767"
tabs-active = "#FFFFFF"
bar = "#1B1A1A"
split = "#292527"
split-active = "#44C9F0"

selection-background = "#1C191A"
selection-foreground = "#44C9F0"
search-match-background = "#44C9F0"
search-match-foreground = "#FFFFFF"
search-focused-match-background = "#E6A003"
search-focused-match-foreground = "#FFFFFF"
hint-background = "#F4BF75"
hint-foreground = "#181818"
